FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ /app/src/

RUN chmod +x /app/src/ingestion/tweet_generator.py

CMD ["python", "/app/src/ingestion/tweet_generator.py"]